added tests with no linter
slavikyd/0410_seminar_temp pull request #1
Opened 2023-10-04 11:23 UTC by errrrvb

no linter provided

2023-10-04 11:24 UTC, slavikyd requested changes
format by flake8

2023-10-04 11:32 UTC, slavikyd approved these changes
noice
![image](https://github.com/slavikyd/0410_seminar_temp/assets/47947352/9d774505-a2dc-48b5-b7ed-53e61c2e014f)

2023-10-04 11:32 UTC, merged

2023-10-06 10:31 UTC, viktoriatyapkova reviewed
Good job!

2023-10-06 10:32 UTC, roganofff reviewed
Pretty code, lots of tests, all cool.